:rotating_light: fix warnings
unit-regression2.cpp:202:34: error: all parameters should be named in a function [hicpp-named-parameter,readability-named-parameter,-warnings-as-errors]
    explicit Foo(const FooAlloc& = FooAlloc()) : value(false) {}
                                 ^
                                  /*unused*/

unit-regression2.cpp:204:10: error: use default member initializer for 'value' [modernize-use-default-member-init,-warnings-as-errors]
    bool value;
         ^
              {false}