github/actions: Remove clang9 on Windows
This currently produces

 In file included from C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.27.29110\include\ciso646:9:
 In file included from C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.27.29110\include\yvals.h:9:
 C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.27.29110\include\yvals_core.h:494:2: error: STL1000: Unexpected compiler version, expected Clang 10.0.0 or newer.
  #error STL1000: Unexpected compiler version, expected Clang 10.0.0 or newer.

and that is very likely due to the new -pedantic flag when compiling.

Let's remove this compiler as it clearly is not meant to be used with
these MSVC headers.